Traceback (most recent call last):
  File "D:/Python/Traceback.py", line 5, in <module>
    inverse(0)
  File "D:/Python/Traceback.py", line 3, in inverse
    return 1/a
ZeroDivisionError: division by zero
